# Build & run in one stage to keep it simple
FROM eclipse-temurin:21-jdk

WORKDIR /app

# Copy source and MySQL driver
COPY src/ src/
COPY lib/mysql-connector-j-9.4.0.jar lib/mysql-connector-j-9.4.0.jar

# Compile
RUN javac -cp lib/mysql-connector-j-9.4.0.jar -d out src/server/AppServer.java

EXPOSE 3050
ENV PORT=3050

CMD ["sh","-lc","java -cp out:lib/mysql-connector-j-9.4.0.jar /src/server/AppServer.java"]
